### ISSUE TITLE
There are duplicate jobs in the repository.py file

### ISSUE THREAD

**Issue by C-Loftus** [internetofwater/scheduler#18]
Using the default pygen.py file, it generates duplicate jobs. This causes dagster to fail since it cannot process the same job twice in the same  repository function like below

```py
@repository
def gleaner():
    ...
```

![image](https://github.com/user-attachments/assets/f53e8a20-021c-4b6c-80b0-4251e5245f64)

**Comment by C-Loftus** [comment]
RISE appears to show up twice in our sitemap. Seems to potentially be our issue

<img width="682" alt="image" src="https://github.com/user-attachments/assets/6c13f4d9-b29e-4ca0-86e3-67214e7d7f9e">

**Comment by C-Loftus** [comment]
fixed for time being by just skipping the second url with the same name but need to check if we need to change our sitemap

**Comment by webb-ben** [comment]
Addressed in https://github.com/internetofwater/scheduler/pull/14

**Comment by C-Loftus** [comment]
addressed in #13
